### ISSUE TITLE
NetCoreHartIpClient repository doesn't exist

### ISSUE THREAD

**Issue by nagilum2007** [FieldCommGroup/Portable-HART-IP-Client#1]
Referring to the documentation for building the Portable HART-IP Client (located here: https://github.com/FieldCommGroup/Portable-HART-IP-Client/blob/main/doc/C-Building%20the%20Portable%20HART-IP%20Client.md), step 1 requires cloning the NetCoreHartIpClient repository. However, when I click on the link, github says the repository doesn't exist.

Is there an updated link to the repository or updated instructions?

**Comment by tjohnston-fcg** [comment]
FieldComm Group decided against releasing the source code for this client. The Windows installer for this client is bundled with the HART Test System and the paid HART-IP Developer Kit.
