### ISSUE TITLE
URL to NetCoreHartIpClient = broken

### ISSUE THREAD

**Issue by DefaultUser0112** [FieldCommGroup/Portable-HART-IP-Client#2]
Dear sir/madam,

The URL to the 'NetCoreHartIpClient'-repo is broken, is there any chance this URL could be fixed-/the 'NetCoreHartIpClient' is reuploaded?

Thanks in advance.

**Comment by tjohnston-fcg** [comment]
FieldComm Group decided against releasing the source code for this client.  The Windows installer for this client is bundled with the HART Test System and the paid HART-IP Developer Kit.
